### ISSUE TITLE
angular.isBoolean is not a function

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/contacts#549]
As reported on the appstore:

after updating to 1.5.1 I only get a spinning wheel when opening the app. it loads the groups, but then nothing moore.
Its on OC 9.1.1

the console showes this:
````
angular.js?v=3f764a2…:13920 TypeError: angular.isBoolean is not a function
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2071:44
    at Array.sort (native)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2057:13
    at fn (eval at compile (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:14817:15), &lt;anonymous&gt;:4:612)
    at regularInterceptedExpression (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:16043:55)
    at Scope.$digest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17515:34)
    at Scope.$apply (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17790:24)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:564:11(anonymous function) @ angular.js?v=3f764a2…:13920(anonymous function) @ angular.js?v=3f764a2…:10467$digest @ angular.js?v=3f764a2…:17542$apply @ angular.js?v=3f764a2…:17790(anonymous function) @ contactList_controller.js:75
2angular.js?v=3f764a2…:13920 TypeError: angular.isBoolean is not a function
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2071:44
    at Array.sort (native)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2057:13
    at fn (eval at compile (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:14817:15), &lt;anonymous&gt;:4:612)
    at regularInterceptedExpression (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:16043:55)
    at Scope.$digest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17515:34)
    at Scope.$apply (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17790:24)
    at done (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:11831:47)
    at completeRequest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:12033:7)
    at XMLHttpRequest.requestLoaded (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:11966:9)(anonymous function) @ angular.js?v=3f764a2…:13920(anonymous function) @ angular.js?v=3f764a2…:10467$digest @ angular.js?v=3f764a2…:17542$apply @ angular.js?v=3f764a2…:17790done @ angular.js?v=3f764a2…:11831completeRequest @ angular.js?v=3f764a2…:12033requestLoaded @ angular.js?v=3f764a2…:11966
