### PR TITLE
angular.isBoolean is unknown

### LINKED ISSUE #549: angular.isBoolean is not a function
As reported on the appstore:

after updating to 1.5.1 I only get a spinning wheel when opening the app. it loads the groups, but then nothing moore.
Its on OC 9.1.1

the console showes this:
````
angular.js?v=3f764a2…:13920 TypeError: angular.isBoolean is not a function
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2071:44
    at Array.sort (native)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2057:13
    at fn (eval at compile (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:14817:15), &lt;anonymous&gt;:4:612)
    at regularInterceptedExpression (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:16043:55)
    at Scope.$digest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17515:34)
    at Scope.$apply (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17790:24)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:564:11(anonymous function) @ angular.js?v=3f764a2…:13920(anonymous function) @ angular.js?v=3f764a2…:10467$digest @ angular.js?v=3f764a2…:17542$apply @ angular.js?v=3f764a2…:17790(anonymous function) @ contactList_controller.js:75
2angular.js?v=3f764a2…:13920 TypeError: angular.isBoolean is not a function
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2071:44
    at Array.sort (native)
    at https://domain.name/apps/contacts/js/public/script.js?v=3f764a290c39eb48074e31bf14e9ad97:2057:13
    at fn (eval at compile (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:14817:15), &lt;anonymous&gt;:4:612)
    at regularInterceptedExpression (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:16043:55)
    at Scope.$digest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17515:34)
    at Scope.$apply (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:17790:24)
    at done (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:11831:47)
    at completeRequest (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:12033:7)
    at XMLHttpRequest.requestLoaded (https://domain.name/apps/contacts/js/vendor/angular/angular.js?v=3f764a290c39eb48074e31bf14e9ad97:11966:9)(anonymous function) @ angular.js?v=3f764a2…:13920(anonymous function) @ angular.js?v=3f764a2…:10467$digest @ angular.js?v=3f764a2…:17542$apply @ angular.js?v=3f764a2…:17790done @ angular.js?v=3f764a2…:11831completeRequest @ angular.js?v=3f764a2…:12033requestLoaded @ angular.js?v=3f764a2…:11966

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #549 

here is the package for easy testing:
https://github.com/owncloud/contacts/releases/download/1.5.2-alpha/contacts.tar.gz

### CODE REVIEW

**Comment by arkascha** [comment]
Does not work for me. 
Installed the linked archive, deleted the assets js file and reloaded the contact apps - still the same issue: an endless spinner instead of a list of contacts. I don't see anything related in the browsers js console. Using oc-9.1.2

**Comment by DeepDiver1975** [comment]
> I don't see anything related in the browsers js console.

so at least the isBoolean issue is gone

**Comment by DeepDiver1975** [comment]
@arkascha how many addressbooks and how many contacts?

**Comment by arkascha** [comment]
3 address book inside owncloud holding 332 contacts in total. 
app version 1.5.0 take a few seconds to load, actually the "no contacts in here" is shown while the spinner is still busy, but then the contacts appear. 
I do not see anything relevant in the server side log files.

**Comment by DeepDiver1975** [comment]
@arkascha was the behavior in 1.4.x the same?

**Comment by arkascha** [comment]
@DeepDiver1975:  
Sorry, I just checked since your question confused me and I have to correct my statement from above: 
I previously had 1.4 installed, not 1.5. In 1.4.0.0 (which I now reinstalled) all works fine for me.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975:
> Sorry, I just checked since your question confused me and I have to correct my statement from above:
> I previously had 1.4 installed, not 1.5. In 1.4.0.0 (which I now reinstalled) all works fine for me.

hmmm - strange ... mind opening a new issue to track this? THX

**Comment by arkascha** [comment]
Done: https://github.com/owncloud/contacts/issues/552
